In [ ]:
                                            # Numpy Assignment 2

In [ ]:
#Q1
#create a 5x5 matrix with row values ranging from 0 to 4

In [1]:
import numpy as np
import pandas as pd

In [2]:
x3 = np.zeros((5,5))
print("Original array:")
print(x3)
print("Row values ranging from 0 to 4.")
x3 += np.arange(5)
print(x3)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#Q2
#multiply a 5x3 matrix by a 3x2 matrix(real matrix product)

In [3]:
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("product of two arrays:")
print(z)

First array:
[[0.66061342 0.70199878 0.82892373]
 [0.69960269 0.51045876 0.08163815]
 [0.76342891 0.26693484 0.36521868]
 [0.27651176 0.12222115 0.04020175]
 [0.01005215 0.1243555  0.51247288]]
Second array:
[[0.27706436 0.30940039]
 [0.44796244 0.54167331]
 [0.71610159 0.85093038]]
product of two arrays:
[[1.09109512 1.29000444]
 [0.48096253 0.56242762]
 [0.59262939 0.69157235]
 [0.16015058 0.18596567]
 [0.42547433 0.50654894]]


In [ ]:
#Q3 

# What is the result of the following expression ? 

In [4]:
0 * np.nan

nan

In [5]:
np.nan == np.nan

False

In [6]:
np.inf > np.nan

False

In [7]:
np.nan - np.nan

nan

In [8]:
np.nan in set ([np.nan])

True

In [9]:
0.3 == 3*0.1

False

In [ ]:
#Q4
#create a 10x10 array with random values and find the minimum and maximum values 

In [14]:
ran = np.random.random((10,10))
ran

array([[0.14871998, 0.99918246, 0.84331984, 0.2326823 , 0.44990556,
        0.27424751, 0.36886987, 0.16877133, 0.18968944, 0.28808863],
       [0.81385388, 0.90034999, 0.29595954, 0.75810747, 0.98987888,
        0.21082498, 0.03919492, 0.45658844, 0.40370634, 0.29362097],
       [0.18535789, 0.23325515, 0.30820513, 0.60018384, 0.74809539,
        0.29489039, 0.05934613, 0.66162454, 0.59457307, 0.03610392],
       [0.50916008, 0.65453747, 0.58389249, 0.97165338, 0.59390032,
        0.7410359 , 0.80083075, 0.6516494 , 0.6532892 , 0.0141429 ],
       [0.759612  , 0.10057411, 0.32432028, 0.31582439, 0.15239896,
        0.17786679, 0.92267678, 0.61423251, 0.74906542, 0.86342975],
       [0.67742966, 0.03653986, 0.21016281, 0.38956323, 0.54987951,
        0.50993114, 0.71904675, 0.78607992, 0.1740031 , 0.5372601 ],
       [0.2051484 , 0.10472946, 0.33901968, 0.70554348, 0.99966863,
        0.79845035, 0.68085012, 0.07937561, 0.96632446, 0.4068419 ],
       [0.37236134, 0.86081068, 0.9521260

In [15]:
print("The minimum value is")
ran.min()

The minimum value is


0.009627612470979652

In [16]:
print("The maximum value is")
ran.max()

The maximum value is


0.9996686267348152

In [ ]:
#Q5
#Create a null vector of size 10 but the fifth value which is 1

In [13]:
x4 = np. zeros(10, dtype=int)
x4[4] = 1 
x4

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])