In [ ]:
                               # Numpy assignment 1

In [ ]:
#Q1. 
# Create an array filled with random values

In [8]:
import numpy as np

rand_nums = np.random.random(10)

rand_nums

array([0.08652857, 0.19593826, 0.04101318, 0.419211  , 0.71258758,
       0.15412112, 0.66307495, 0.15237829, 0.1749573 , 0.82776786])

In [ ]:
#Q2.
# Create a rank 1 array
# Print "(3,)"
# Print "1 2 3"
# Change an element of the array
# Create a rank 2 array

In [ ]:
# Create a rank 1 array

In [53]:
rank_1 = np.array([1,2,3,4,5])

rank_1                                 # A simple list is a rank 1 array

array([1, 2, 3, 4, 5])

In [ ]:
# Print "(3,)"

In [54]:
print(rank_1[3,])

4


In [ ]:
# Print "1 2 3"

In [55]:
print(rank_1[0:3])

[1 2 3]


In [ ]:
# Change an element of the array

In [56]:
rank_1[2]=33

print(rank_1)

[ 1  2 33  4  5]


In [ ]:
# Create a rank 2 array

In [4]:
rank_2 = np.array([11,22,33,44,55], ndmin=2)

rank_2

array([[11, 22, 33, 44, 55]])

In [ ]:
#Q3
#Create an array of all ones
#Create a constant array
#Create a 2x2 identity matrix

In [ ]:
#Create an array of all ones

In [65]:
 np.ones(5)



array([1., 1., 1., 1., 1.])

In [ ]:
#Create a constant array

In [64]:
np.full((4,4), 23)



array([[23, 23, 23, 23],
       [23, 23, 23, 23],
       [23, 23, 23, 23],
       [23, 23, 23, 23]])

In [ ]:
#Create a 2x2 identity matrix

In [67]:
np.identity(2, dtype=int)          #dtype = int because by default it gives float values

array([[1, 0],
       [0, 1]])

In [ ]:
#Q4
#Create the following rank 2 array with shape (3, 4)
#Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2)

In [18]:
array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(array_2d)

sub_array = array_2d[:2,1:3]

print("the sub_array is:- ")

print(sub_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
the sub_array is:- 
[[2 3]
 [6 7]]


In [21]:
#Q.5
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
#sum, divide,product,divide,square root

In [29]:
x

array([[1., 2.],
       [3., 4.]])

In [30]:
y

array([[5., 6.],
       [7., 8.]])

In [ ]:
#sum

In [27]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
# divide

In [28]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# multiply

In [31]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

In [ ]:
#subtract

In [32]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [ ]:
# square root

In [34]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [35]:
np.sqrt(y)

array([[1.        , 1.18920712],
       [1.31607401, 1.41421356]])

In [37]:
#Q6
v = np.array([1, 0, 1])
# Stack 4 copies of v on top of each other
#Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [ ]:
# Stack 4 copies of v on top of each other

In [39]:
v1 = np.tile(v, (4,1))
v1

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [ ]:
#Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [70]:
A = np.array([1,2,3])
np.tile(A,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [71]:
len(A)

3

In [ ]:
#Q7
#Create an array of the first 10 odd integers.
# Find intersection of a and b

In [ ]:
#Create an array of the first 10 odd integers.

In [81]:
list1 = np.array(range(0,20))
odd_num = list1[ list1%2 == 1 ]
odd_num

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#Q8
##Reshape 1d array a to 2d array of 2X5
##Create a numpy array to list and vice versa

In [ ]:
##Reshape 1d array a to 2d array of 2X5

In [82]:
one_d = np.array(range(0,10))
one_d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
one_d.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
##Create a numpy array to list and vice versa

In [84]:
num_arr = np.array(range(0,10))
num_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
list(num_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [86]:
set(num_arr)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [87]:
tuple(num_arr)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [91]:
dict(enumerate(num_arr))

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}

In [ ]:
#Q9
#Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [100]:
x2 = np.ones((10,10), dtype = int)
print("Original array:")
print(x2)
print("1 on the border and 0 inside in the array")
x2[1:-1,1:-1] = 0
print(x2)

Original array:
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
1 on the border and 0 inside in the array
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
#Q10
# Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [99]:
print("Checkerboard pattern:")
x = np.zeros((10,10),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]
